server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.12:3306/big_market
    username: root
    password: 13433026660

app:
  config:
    CrossOrigin: '*'

# Redis
redis:
  # redis的地址
  address: redis://192.168.0.12:6379
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# GLM
glm:
  apiKey: a79a6e151dc42dd50142f25a409bca54.JzVqaCdjk1uXC62Z