#file: noinspection SpringBootApplicationYaml

server:
  port: 8090

logging:
  level:
    root: INFO  # 设置全局日志级别
    app.xlog.ggbond: INFO  # 设置包级别日志级别
    org.springframework: WARN  # 设置spring的日志级别

sa-token:
  token-name: satoken  # token 名称（同时也是 cookie 名称）
  timeout: 2592000  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  active-timeout: -1  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  is-concurrent: true  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-share: false  # 在多人登录同一账号时，是否共用一个 token（因为同一个人可能参加多个活动）
  token-style: uuid  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  is-log: true  # 是否输出操作日志

liteflow:
  rule-source: application-liteflow-raffle.xml, application-liteflow-activity.xml

xxl:
  job:
    admin:
      addresses: http://172.17.0.1:9384/xxl-job-admin  # 调度中心的地址
    # 调度中心的访问令牌，为空则不启用
    accessToken: default_token
    # 执行器配置
    executor:
      appName: big-market-executor  # 该执行器的名称
      address: ""  # 该执行器的外部访问地址，如果为空，则该执行器只能被本地访问
      ip: ""  # 执行器的IP地址，为空则为本机ip
      port: 9999  # 执行器的端口，调度中心在调度任务时会访问该端口
      logPath: /data/appLogs/xxl-job/jobHandler  # 执行器日志存储路径
      logRetentionDays: 30  # 执行器日志保存天数

dubbo:
  application:
    name: big-market-app  # 应用名称
  registry:
    address: nacos://localhost:8848  # 服务注册中心的地址
    parameters.namespace: f1680a4a-b6f6-49ec-a747-aa35a219570a
    register-mode: all  # 注册模式
  config-center:
    address: nacos://localhost:8848  # 配置中心的地址，用于集中管理、动态调整 Dubbo 的配置信息