server:
  port: 8090

# 日志
logging:
  level:
    root: INFO  # 设置全局日志级别
    app.xlog.ggbond: INFO  # 设置包级别日志级别
    org.springframework: WARN  # 设置spring的日志级别

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.12:3306/big_market
    username: root
    password: 13433026660

# Redis
redis:
  address: redis://192.168.0.12:6379
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# Sa-Token
sa-token:
  token-name: satoken  # token 名称（同时也是 cookie 名称）
  timeout: 2592000  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  active-timeout: -1  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  is-concurrent: true  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-share: true  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  token-style: uuid  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  is-log: true  # 是否输出操作日志

# liteFlow编排
liteflow:
  rule-source: application-liteflow-raffleFilter.xml

# GLM
glm:
  apiKey: a79a6e151dc42dd50142f25a409bca54.JzVqaCdjk1uXC62Z