# 装配 curl -X GET "http://localhost:8090/api/assemble/v1/assembleRaffleAll?strategyId=1"
GET http://localhost:8090/api/raffle/assemble/v1/assembleRaffleAll?strategyId=10001

###

# 查询奖品列表 curl -X GET "http://localhost:8090/api/award/v2/queryAwardList?strategyId=1"
GET http://localhost:8090/api/raffle/dispatch/v2/queryAwardList?activityId=10001

###

# 抽取奖品 curl -X GET "http://localhost:8090/api/award/v2/getAward?userId=123&strategyId=1"
GET http://localhost:8090/api/raffle/dispatch/v2/getAward?activityId=10001

###

# 登录 curl -X GET "http://localhost:8090/api/user/v1/doLogin?userId=123&password=your_password"
GET http://localhost:8090/api/security/user/v1/doLogin?activityId=10001&userId=404&password=404

###

# curl -X GET "http://localhost:8080/api/test/v1/bigModelAnswer"
GET http://localhost:8090/api/test/v1/bigModelAnswer

###

# curl -X GET "http://localhost:8090/api/test/v1/isTokenExpired"
GET http://localhost:8090/api/test/v1/isTokenExpired

###

# curl -X GET "http://localhost:8080/api/raffle/dispatch/v1/getWinningAwardsInfo" -H "Accept: text/event-stream"
GET http://localhost:8090/api/raffle/dispatch/v1/getWinningAwardsInfo?activityId=10001

###









