# curl -X GET "http://localhost:8090/api/assemble/v1/assembleRaffleAll?strategyId=1"
GET http://localhost:8090/api/raffle/assemble/v1/assembleRaffleAll?strategyId=10001

###

# curl -X GET "http://localhost:8090/api/award/v1/queryAwardList?strategyId=1"
GET http://localhost:8090/api/raffle/dispatch/v1/queryAwardList?strategyId=10001

###

# curl -X GET "http://localhost:8090/api/award/v1/getAward?userId=123&strategyId=1"
GET http://localhost:8090/api/raffle/dispatch/v1/getAward?strategyId=10001

###

# curl -X GET "http://localhost:8090/api/user/v1/doLogin?userId=123&password=your_password"
GET http://localhost:8090/api/security/user/v1/doLogin?userId=404&password=404

###

# curl -X GET "http://localhost:8080/api/test/v1/bigModelAnswer"
GET http://localhost:8090/api/test/v1/bigModelAnswer

###









