# 命令执行 docker-compose -f docker-compose-app.yml up -d
#  docker run -p 8090:8090 -d --restart=always --name big-market big-market:1.1.0

x-variables:
  big-market-version: 1962883041612/big-market:1.0.1
  big-market-client-version: 1962883041612/big-market-client:1.0.1

version: '3.8'
services:
  # 后端应用
  big-market-app:
    image: 1962883041612/big-market:1.0.1
    container_name: big-market
    restart: always
    ports:
      - "8080:8090"
    environment:
      - TZ=PRC
    networks:
      - big-market-network
      - global-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  # 前端应用
  big-market-client:
    image: 1962883041612/big-market-client:1.0.1
    container_name: big-market-client
    restart: always
    networks:
      - big-market-network
      - global-network
    ports:
      - 5173:5173
  # kafka
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0  # 节点 ID，单节点配置为 0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker  # 同时作为 controller 和 broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER  # 设置 broker 监听器名称
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  # 设置 controller 监听器名称
      - KAFKA_CFG_LISTENERS=BROKER://:9092,CONTROLLER://:9093  # 设置broker和controller监听器的端口
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://localhost:9092,CONTROLLER://localhost:9093  # 广告监听器，确保外部可以访问 broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT  # 使用 PLAINTEXT 协议
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093  # 控制器选举设置，单机模式只需一个节点
      - KAFKA_KRAFT_CLUSTER_ID=big-market-cluster  # 设置集群ID

networks:
  big-market-network:
    driver: bridge
  global-network:
    driver: bridge
